name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
            distribution: 'graalvm'
            java-version: '23'
            github-token: ${{ secrets.GITHUB_TOKEN }}
            native-image-job-reports: 'true'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build distZip
      - uses: actions/upload-artifact@v4
        with:
          name: distribution-zips-${{ matrix.os }}
          path: "**/build/distributions/*.zip"
